apiVersion: v1
kind: Service
metadata:
  labels:
    app: epi-k8s-demo
  name: epi-k8s-demo
spec:
  ports:
  - port: 80
    protocol: TCP
    nodePort: 30080
    name: http
  - port: 443
    protocol: TCP
    nodePort: 30443
    name: https
  type: LoadBalancer
  selector:
    app: epi-k8s-demo
status:
  loadBalancer: {}
